version: '3'
services:
  dictation-buddy:
    container_name: dictation-buddy
    image: nsu_dictation-buddy:latest
    ports:
      - "8501:8501"
    volumes:
      - ./audio_files:/app/audio_files
    restart: unless-stopped

