version: '3'
services:
  dictation-buddy:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: dictation-buddy
    ports:
      - "8501:8501"
    volumes:
      - ./audio_files:/app/audio_files
    restart: unless-stopped

